// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	context "context"
	user "sample/twirp/rpc/user"

	mock "github.com/stretchr/testify/mock"
)

// UserService is an autogenerated mock type for the UserService type
type UserService struct {
	mock.Mock
}

// CreateUser provides a mock function with given fields: _a0, _a1
func (_m *UserService) CreateUser(_a0 context.Context, _a1 *user.User) (*user.Response, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *user.Response
	if rf, ok := ret.Get(0).(func(context.Context, *user.User) *user.Response); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.Response)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *user.User) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUser provides a mock function with given fields: _a0, _a1
func (_m *UserService) GetUser(_a0 context.Context, _a1 *user.Request) (*user.Response, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *user.Response
	if rf, ok := ret.Get(0).(func(context.Context, *user.Request) *user.Response); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.Response)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *user.Request) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Login provides a mock function with given fields: _a0, _a1
func (_m *UserService) Login(_a0 context.Context, _a1 *user.LoginReq) (*user.Response, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *user.Response
	if rf, ok := ret.Get(0).(func(context.Context, *user.LoginReq) *user.Response); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.Response)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *user.LoginReq) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
